
create TABLE IF NOT EXISTS USERS (
    ID IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) NOT NULL,
    ENABLED INT NOT NULL
);


create TABLE IF NOT EXISTS AUTHORITIES (
    ID IDENTITY PRIMARY KEY,
    USERNAME VARCHAR(45) NOT NULL,
    AUTHORITY VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID)
);

insert into AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('john', 'write');

insert into USERS (USERNAME, PASSWORD, ENABLED)
VALUES ('john', '123', '1');

